// <auto-generated />
using System;
using HealthOps_Project.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HealthOps_Project.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HealthOps_Project.Models.Admission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AdmissionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("BedId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DischargeDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("WardId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BedId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.HasIndex("WardId");

                    b.ToTable("Admissions");
                });

            modelBuilder.Entity("HealthOps_Project.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateRegistered")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StaffId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("HealthOps_Project.Models.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentId"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("AppointmentTime")
                        .HasColumnType("time");

                    b.Property<string>("DoctorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PatientEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("PatientIdNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PatientPhone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.HasKey("AppointmentId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("HealthOps_Project.Models.Bed", b =>
                {
                    b.Property<int>("BedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BedId"));

                    b.Property<string>("BedNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<int?>("PatientId")
                        .HasColumnType("int");

                    b.Property<int?>("RoomId")
                        .HasColumnType("int");

                    b.Property<int?>("WardId")
                        .HasColumnType("int");

                    b.HasKey("BedId");

                    b.HasIndex("PatientId")
                        .IsUnique()
                        .HasFilter("[PatientId] IS NOT NULL");

                    b.HasIndex("RoomId");

                    b.HasIndex("WardId");

                    b.ToTable("Beds");
                });

            modelBuilder.Entity("HealthOps_Project.Models.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiverId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("HealthOps_Project.Models.Consumable", b =>
                {
                    b.Property<int>("ConsumableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConsumableId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ConsumableId");

                    b.ToTable("Consumables");

                    b.HasData(
                        new
                        {
                            ConsumableId = 1,
                            Description = "Latex gloves, medium size, 100 per box",
                            Name = "Gloves",
                            Unit = "Box"
                        },
                        new
                        {
                            ConsumableId = 2,
                            Description = "5ml disposable syringes, 50 per pack",
                            Name = "Syringes",
                            Unit = "Pack"
                        },
                        new
                        {
                            ConsumableId = 3,
                            Description = "Disposable linen savers for beds, 10 per roll",
                            Name = "Linen Savers",
                            Unit = "Roll"
                        },
                        new
                        {
                            ConsumableId = 4,
                            Description = "Sterile gauze bandages, 10 per pack",
                            Name = "Bandages",
                            Unit = "Pack"
                        },
                        new
                        {
                            ConsumableId = 5,
                            Description = "Isopropyl alcohol swabs, 200 per box",
                            Name = "Alcohol Swabs",
                            Unit = "Box"
                        },
                        new
                        {
                            ConsumableId = 6,
                            Description = "Sterile gauze pads 10x10cm, 25 per pack",
                            Name = "Gauze Pads",
                            Unit = "Pack"
                        },
                        new
                        {
                            ConsumableId = 7,
                            Description = "Hypoallergenic medical tape, 10m per roll",
                            Name = "Medical Tape",
                            Unit = "Roll"
                        });
                });

            modelBuilder.Entity("HealthOps_Project.Models.ConsumableRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConsumableId")
                        .HasColumnType("int");

                    b.Property<int>("QuantityRequested")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReceivedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("WardName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ConsumableId");

                    b.ToTable("ConsumableRequests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConsumableId = 2,
                            QuantityRequested = 30,
                            RequestedAt = new DateTime(2025, 10, 19, 15, 28, 14, 595, DateTimeKind.Utc).AddTicks(7273),
                            Status = "Pending",
                            WardName = "Ward B"
                        },
                        new
                        {
                            Id = 2,
                            ConsumableId = 1,
                            QuantityRequested = 10,
                            ReceivedAt = new DateTime(2025, 10, 19, 13, 28, 14, 595, DateTimeKind.Utc).AddTicks(7284),
                            RequestedAt = new DateTime(2025, 10, 18, 17, 28, 14, 595, DateTimeKind.Utc).AddTicks(7277),
                            Status = "Approved",
                            WardName = "Emergency"
                        },
                        new
                        {
                            Id = 3,
                            ConsumableId = 4,
                            QuantityRequested = 15,
                            ReceivedAt = new DateTime(2025, 10, 19, 16, 28, 14, 595, DateTimeKind.Utc).AddTicks(7288),
                            RequestedAt = new DateTime(2025, 10, 17, 17, 28, 14, 595, DateTimeKind.Utc).AddTicks(7287),
                            Status = "Received",
                            WardName = "Ward A"
                        },
                        new
                        {
                            Id = 4,
                            ConsumableId = 5,
                            QuantityRequested = 5,
                            RequestedAt = new DateTime(2025, 10, 19, 14, 28, 14, 595, DateTimeKind.Utc).AddTicks(7290),
                            Status = "Pending",
                            WardName = "ICU"
                        });
                });

            modelBuilder.Entity("HealthOps_Project.Models.ContactMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ContactMessages");
                });

            modelBuilder.Entity("HealthOps_Project.Models.Diagnosis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int?>("SymptomId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.HasIndex("SymptomId");

                    b.ToTable("Diagnoses");
                });

            modelBuilder.Entity("HealthOps_Project.Models.Discharge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DischargeDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("WardId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("WardId");

                    b.ToTable("Discharges");
                });

            modelBuilder.Entity("HealthOps_Project.Models.Doctor", b =>
                {
                    b.Property<int>("DoctorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DoctorId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("DoctorId");

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("HealthOps_Project.Models.DoctorInstruction", b =>
                {
                    b.Property<int>("DoctorInstructionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DoctorInstructionId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DoctorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("VisitDate")
                        .HasColumnType("datetime2");

                    b.HasKey("DoctorInstructionId");

                    b.HasIndex("PatientId");

                    b.ToTable("DoctorInstructions");
                });

            modelBuilder.Entity("HealthOps_Project.Models.EmailMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Subject")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToEmail")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EmailMessages");
                });

            modelBuilder.Entity("HealthOps_Project.Models.InsuranceProvider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("InsuranceProviders");
                });

            modelBuilder.Entity("HealthOps_Project.Models.Medication", b =>
                {
                    b.Property<int>("MedicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MedicationId"));

                    b.Property<int>("DeletionStatus")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Schedule")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("MedicationId");

                    b.ToTable("Medications");
                });

            modelBuilder.Entity("HealthOps_Project.Models.MedicationAdministration", b =>
                {
                    b.Property<int>("MedicationAdministrationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MedicationAdministrationId"));

                    b.Property<DateTime>("AdministeredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("AdministeredBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MedicationId")
                        .HasColumnType("int");

                    b.Property<string>("MedicationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("PrescriptionId")
                        .HasColumnType("int");

                    b.Property<int?>("PrescriptionId1")
                        .HasColumnType("int");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ScheduleLevel")
                        .HasColumnType("int");

                    b.HasKey("MedicationAdministrationId");

                    b.HasIndex("MedicationId");

                    b.HasIndex("PatientId");

                    b.HasIndex("PrescriptionId");

                    b.HasIndex("PrescriptionId1");

                    b.ToTable("MedicationAdministrations");
                });

            modelBuilder.Entity("HealthOps_Project.Models.MedicationDelivery", b =>
                {
                    b.Property<int>("DeliveryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeliveryId"));

                    b.Property<string>("BatchNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DeliveredAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeliveredQuantity")
                        .HasColumnType("int");

                    b.Property<int?>("ExpectedQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<int>("MedicationId")
                        .HasColumnType("int");

                    b.Property<string>("MedicationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderDeliveryItemId")
                        .HasColumnType("int");

                    b.Property<int>("PrescriptionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReceivedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReceivedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReceivedQuantity")
                        .HasColumnType("int");

                    b.Property<int>("ScriptId")
                        .HasColumnType("int");

                    b.HasKey("DeliveryId");

                    b.HasIndex("MedicationId");

                    b.HasIndex("PrescriptionId");

                    b.HasIndex("ScriptId");

                    b.ToTable("MedicationDeliveries");
                });

            modelBuilder.Entity("HealthOps_Project.Models.NonScheduledMedication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdministeredBy")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("AdministeredDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MedicationId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MedicationId");

                    b.ToTable("NonScheduledMedications");
                });

            modelBuilder.Entity("HealthOps_Project.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("HealthOps_Project.Models.NurseInstruction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Instruction")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("NurseName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("NurseInstructions");
                });

            modelBuilder.Entity("HealthOps_Project.Models.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("AdmissionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Age")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Allergies")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("BedId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DischargeDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DoctorUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("EmergencyContact")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MedicalHistory")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("RoomNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SouthAfricanID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WardId")
                        .HasColumnType("int");

                    b.HasKey("PatientId");

                    b.HasIndex("DoctorUserId");

                    b.HasIndex("WardId");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            PatientId = 1,
                            Address = "123 Main Street, Johannesburg",
                            AdmissionDate = new DateTime(2025, 10, 14, 17, 28, 14, 595, DateTimeKind.Utc).AddTicks(6751),
                            Age = "38",
                            Allergies = "Penicillin, Shellfish",
                            DOB = new DateTime(1985, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "james@email.com",
                            EmergencyContact = "0729876543",
                            FirstName = "James",
                            Gender = "Male",
                            IsActive = true,
                            LastName = "Wilson",
                            MedicalHistory = "Hypertension, Type 2 Diabetes",
                            PhoneNumber = "0711234567",
                            RoomNumber = "101A",
                            SouthAfricanID = "8501015123089"
                        },
                        new
                        {
                            PatientId = 2,
                            Address = "456 Oak Avenue, Cape Town",
                            AdmissionDate = new DateTime(2025, 10, 17, 17, 28, 14, 595, DateTimeKind.Utc).AddTicks(6780),
                            Age = "33",
                            Allergies = "Aspirin, Dust mites",
                            DOB = new DateTime(1990, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sarah@email.com",
                            EmergencyContact = "0831234567",
                            FirstName = "Sarah",
                            Gender = "Female",
                            IsActive = true,
                            LastName = "Johnson",
                            MedicalHistory = "Asthma, Migraines",
                            PhoneNumber = "0824567890",
                            RoomNumber = "205B",
                            SouthAfricanID = "9005154123085"
                        },
                        new
                        {
                            PatientId = 3,
                            Address = "789 Pine Road, Durban",
                            AdmissionDate = new DateTime(2025, 10, 18, 17, 28, 14, 595, DateTimeKind.Utc).AddTicks(6789),
                            Age = "35",
                            Allergies = "Ibuprofen, Latex",
                            DOB = new DateTime(1988, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "robert@email.com",
                            EmergencyContact = "0745566778",
                            FirstName = "Robert",
                            Gender = "Male",
                            IsActive = true,
                            LastName = "Brown",
                            MedicalHistory = "High cholesterol, Back pain",
                            PhoneNumber = "0741122334",
                            RoomNumber = "312C",
                            SouthAfricanID = "8802206123087"
                        },
                        new
                        {
                            PatientId = 4,
                            Address = "321 Beach Road, Port Elizabeth",
                            AdmissionDate = new DateTime(2025, 10, 19, 17, 28, 14, 595, DateTimeKind.Utc).AddTicks(6797),
                            Age = "31",
                            Allergies = "None known",
                            DOB = new DateTime(1992, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "lisa@email.com",
                            EmergencyContact = "0765544332",
                            FirstName = "Lisa",
                            Gender = "Female",
                            IsActive = true,
                            LastName = "Davis",
                            MedicalHistory = "Anxiety, Insomnia",
                            PhoneNumber = "0769988776",
                            RoomNumber = "108D",
                            SouthAfricanID = "9208103123081"
                        },
                        new
                        {
                            PatientId = 5,
                            Address = "654 Mountain View, Pretoria",
                            AdmissionDate = new DateTime(2025, 10, 9, 17, 28, 14, 595, DateTimeKind.Utc).AddTicks(6803),
                            Age = "36",
                            Allergies = "Pollen, Cat dander",
                            DOB = new DateTime(1987, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DischargeDate = new DateTime(2025, 10, 17, 17, 28, 14, 595, DateTimeKind.Utc).AddTicks(6805),
                            Email = "michael@email.com",
                            EmergencyContact = "0732211334",
                            FirstName = "Michael",
                            Gender = "Male",
                            IsActive = false,
                            LastName = "Taylor",
                            MedicalHistory = "GERD, Seasonal allergies",
                            PhoneNumber = "0736655443",
                            RoomNumber = "209E",
                            SouthAfricanID = "8706301123083"
                        });
                });

            modelBuilder.Entity("HealthOps_Project.Models.PatientHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("PatientHistories");
                });

            modelBuilder.Entity("HealthOps_Project.Models.PatientMovement", b =>
                {
                    b.Property<int>("MovementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovementId"));

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("MovementDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MovementType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.HasKey("MovementId");

                    b.HasIndex("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("PatientMovement");
                });

            modelBuilder.Entity("HealthOps_Project.Models.Prescription", b =>
                {
                    b.Property<int>("PrescriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrescriptionId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DoctorId")
                        .HasColumnType("int");

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MedicationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("PrescribingDoctor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("PrescriptionId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Prescriptions");

                    b.HasData(
                        new
                        {
                            PrescriptionId = 1,
                            CreatedAt = new DateTime(2025, 10, 14, 17, 28, 14, 595, DateTimeKind.Utc).AddTicks(7023),
                            Dosage = "500mg",
                            EndDate = new DateTime(2025, 10, 24, 17, 28, 14, 595, DateTimeKind.Utc).AddTicks(7019),
                            Frequency = "Every 8 hours",
                            Instructions = "Take after meals with plenty of water",
                            MedicationName = "Paracetamol 500mg",
                            Notes = "Patient has mild fever",
                            PatientId = 1,
                            PrescribingDoctor = "Dr John Doe",
                            Priority = "Routine",
                            Quantity = 30,
                            StartDate = new DateTime(2025, 10, 14, 17, 28, 14, 595, DateTimeKind.Utc).AddTicks(7017),
                            Status = "Active",
                            UpdatedAt = new DateTime(2025, 10, 14, 17, 28, 14, 595, DateTimeKind.Utc).AddTicks(7025)
                        },
                        new
                        {
                            PrescriptionId = 2,
                            CreatedAt = new DateTime(2025, 10, 17, 17, 28, 14, 595, DateTimeKind.Utc).AddTicks(7033),
                            Dosage = "250mg",
                            EndDate = new DateTime(2025, 10, 27, 17, 28, 14, 595, DateTimeKind.Utc).AddTicks(7031),
                            Frequency = "Three times daily",
                            Instructions = "Complete the full course even if feeling better",
                            MedicationName = "Amoxicillin 250mg",
                            Notes = "For bacterial infection",
                            PatientId = 2,
                            PrescribingDoctor = "Dr John Doe",
                            Priority = "Urgent",
                            Quantity = 21,
                            StartDate = new DateTime(2025, 10, 17, 17, 28, 14, 595, DateTimeKind.Utc).AddTicks(7029),
                            Status = "Active",
                            UpdatedAt = new DateTime(2025, 10, 17, 17, 28, 14, 595, DateTimeKind.Utc).AddTicks(7034)
                        },
                        new
                        {
                            PrescriptionId = 3,
                            CreatedAt = new DateTime(2025, 10, 18, 17, 28, 14, 595, DateTimeKind.Utc).AddTicks(7041),
                            Dosage = "400mg",
                            EndDate = new DateTime(2025, 11, 2, 17, 28, 14, 595, DateTimeKind.Utc).AddTicks(7039),
                            Frequency = "As needed",
                            Instructions = "Take for pain relief, maximum 3 times per day",
                            MedicationName = "Ibuprofen 400mg",
                            Notes = "For back pain management",
                            PatientId = 3,
                            PrescribingDoctor = "Dr Sarah Johnson",
                            Priority = "Routine",
                            Quantity = 20,
                            StartDate = new DateTime(2025, 10, 18, 17, 28, 14, 595, DateTimeKind.Utc).AddTicks(7038),
                            Status = "Pending",
                            UpdatedAt = new DateTime(2025, 10, 18, 17, 28, 14, 595, DateTimeKind.Utc).AddTicks(7042)
                        },
                        new
                        {
                            PrescriptionId = 4,
                            CreatedAt = new DateTime(2025, 10, 19, 17, 28, 14, 595, DateTimeKind.Utc).AddTicks(7049),
                            Dosage = "100mcg",
                            EndDate = new DateTime(2025, 11, 18, 17, 28, 14, 595, DateTimeKind.Utc).AddTicks(7047),
                            Frequency = "Twice daily",
                            Instructions = "Use one puff in morning and evening",
                            MedicationName = "Ventolin Inhaler",
                            Notes = "Asthma maintenance medication",
                            PatientId = 1,
                            PrescribingDoctor = "Dr John Doe",
                            Priority = "High",
                            Quantity = 1,
                            StartDate = new DateTime(2025, 10, 19, 17, 28, 14, 595, DateTimeKind.Utc).AddTicks(7046),
                            Status = "Processed",
                            UpdatedAt = new DateTime(2025, 10, 19, 17, 28, 14, 595, DateTimeKind.Utc).AddTicks(7050)
                        },
                        new
                        {
                            PrescriptionId = 5,
                            CreatedAt = new DateTime(2025, 10, 9, 17, 28, 14, 595, DateTimeKind.Utc).AddTicks(7056),
                            Dosage = "20mg",
                            EndDate = new DateTime(2025, 11, 8, 17, 28, 14, 595, DateTimeKind.Utc).AddTicks(7054),
                            Frequency = "Once daily",
                            Instructions = "Take before breakfast",
                            MedicationName = "Omeprazole 20mg",
                            Notes = "For acid reflux",
                            PatientId = 2,
                            PrescribingDoctor = "Dr Sarah Johnson",
                            Priority = "Medium",
                            Quantity = 30,
                            StartDate = new DateTime(2025, 10, 9, 17, 28, 14, 595, DateTimeKind.Utc).AddTicks(7053),
                            Status = "Dispensed",
                            UpdatedAt = new DateTime(2025, 10, 14, 17, 28, 14, 595, DateTimeKind.Utc).AddTicks(7057)
                        },
                        new
                        {
                            PrescriptionId = 6,
                            CreatedAt = new DateTime(2025, 10, 16, 17, 28, 14, 595, DateTimeKind.Utc).AddTicks(7064),
                            Dosage = "40mg",
                            EndDate = new DateTime(2025, 11, 15, 17, 28, 14, 595, DateTimeKind.Utc).AddTicks(7062),
                            Frequency = "Once daily",
                            Instructions = "Take at bedtime",
                            MedicationName = "Atorvastatin 40mg",
                            Notes = "For cholesterol management",
                            PatientId = 4,
                            PrescribingDoctor = "Dr John Doe",
                            Priority = "High",
                            Quantity = 30,
                            StartDate = new DateTime(2025, 10, 16, 17, 28, 14, 595, DateTimeKind.Utc).AddTicks(7061),
                            Status = "New",
                            UpdatedAt = new DateTime(2025, 10, 16, 17, 28, 14, 595, DateTimeKind.Utc).AddTicks(7073)
                        });
                });

            modelBuilder.Entity("HealthOps_Project.Models.PrescriptionDelivery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PrescriptionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("PrescriptionId");

                    b.ToTable("PrescriptionDeliveries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PrescriptionId = 1,
                            RequestedAt = new DateTime(2025, 10, 19, 15, 28, 14, 595, DateTimeKind.Utc).AddTicks(7126),
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 2,
                            DeliveredAt = new DateTime(2025, 10, 19, 13, 28, 14, 595, DateTimeKind.Utc).AddTicks(7132),
                            PrescriptionId = 2,
                            RequestedAt = new DateTime(2025, 10, 18, 17, 28, 14, 595, DateTimeKind.Utc).AddTicks(7131),
                            Status = "Delivered"
                        },
                        new
                        {
                            Id = 3,
                            PrescriptionId = 4,
                            RequestedAt = new DateTime(2025, 10, 19, 16, 28, 14, 595, DateTimeKind.Utc).AddTicks(7135),
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 4,
                            DeliveredAt = new DateTime(2025, 10, 18, 17, 28, 14, 595, DateTimeKind.Utc).AddTicks(7148),
                            PrescriptionId = 5,
                            RequestedAt = new DateTime(2025, 10, 17, 17, 28, 14, 595, DateTimeKind.Utc).AddTicks(7147),
                            Status = "Delivered"
                        },
                        new
                        {
                            Id = 5,
                            PrescriptionId = 6,
                            RequestedAt = new DateTime(2025, 10, 19, 11, 28, 14, 595, DateTimeKind.Utc).AddTicks(7151),
                            Status = "Cancelled"
                        });
                });

            modelBuilder.Entity("HealthOps_Project.Models.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomId"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("RoomId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("HealthOps_Project.Models.ScheduledMedication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdministeredBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("AdministeredDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MedicationId")
                        .HasColumnType("int");

                    b.Property<int>("ScheduledMedicationStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MedicationId");

                    b.ToTable("ScheduledMedications");
                });

            modelBuilder.Entity("HealthOps_Project.Models.Script", b =>
                {
                    b.Property<int>("ScriptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScriptId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ForwardedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ForwardedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MedicationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("PrescribingDoctor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ScriptId");

                    b.HasIndex("PatientId");

                    b.ToTable("Scripts");
                });

            modelBuilder.Entity("HealthOps_Project.Models.Stocktake", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConsumableId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateTaken")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuantityCounted")
                        .HasColumnType("int");

                    b.Property<string>("WardName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ConsumableId");

                    b.ToTable("Stocktakes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConsumableId = 1,
                            DateTaken = new DateTime(2025, 10, 18, 17, 28, 14, 595, DateTimeKind.Utc).AddTicks(7342),
                            Notes = "Initial stocktake - all items accounted for",
                            QuantityCounted = 50,
                            WardName = "Ward A"
                        },
                        new
                        {
                            Id = 2,
                            ConsumableId = 2,
                            DateTaken = new DateTime(2025, 10, 19, 17, 28, 14, 595, DateTimeKind.Utc).AddTicks(7346),
                            Notes = "Minor discrepancy noted - 5 units missing",
                            QuantityCounted = 95,
                            WardName = "Ward B"
                        },
                        new
                        {
                            Id = 3,
                            ConsumableId = 5,
                            DateTaken = new DateTime(2025, 10, 19, 15, 28, 14, 595, DateTimeKind.Utc).AddTicks(7348),
                            Notes = "2 units damaged, removed from stock",
                            QuantityCounted = 148,
                            WardName = "Emergency"
                        });
                });

            modelBuilder.Entity("HealthOps_Project.Models.Symptom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("Symptoms");
                });

            modelBuilder.Entity("HealthOps_Project.Models.Treatment", b =>
                {
                    b.Property<int>("TreatmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TreatmentId"));

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("TreatmentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TreatmentType")
                        .HasColumnType("int");

                    b.HasKey("TreatmentId");

                    b.HasIndex("PatientId");

                    b.ToTable("Treatments");
                });

            modelBuilder.Entity("HealthOps_Project.Models.Visitation", b =>
                {
                    b.Property<int>("VisitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VisitId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DoctorId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Purpose")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("ScheduledTime")
                        .HasColumnType("time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("VisitDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VisitorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.HasKey("VisitId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Visitations");
                });

            modelBuilder.Entity("HealthOps_Project.Models.VitalSign", b =>
                {
                    b.Property<int>("VitalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VitalId"));

                    b.Property<string>("BloodPressure")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("BloodSugar")
                        .HasColumnType("int");

                    b.Property<int?>("HeartRate")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OxygenSaturation")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("RecordedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("RecordedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Temperature")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("VitalId");

                    b.HasIndex("PatientId");

                    b.ToTable("VitalSigns");
                });

            modelBuilder.Entity("HealthOps_Project.Models.Ward", b =>
                {
                    b.Property<int>("WardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WardId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("WardId");

                    b.ToTable("Wards");
                });

            modelBuilder.Entity("HealthOps_Project.Models.WardStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConsumableId")
                        .HasColumnType("int");

                    b.Property<int>("QuantityOnHand")
                        .HasColumnType("int");

                    b.Property<string>("WardName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ConsumableId");

                    b.ToTable("WardStocks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConsumableId = 1,
                            QuantityOnHand = 50,
                            WardName = "Ward A"
                        },
                        new
                        {
                            Id = 2,
                            ConsumableId = 2,
                            QuantityOnHand = 100,
                            WardName = "Ward B"
                        },
                        new
                        {
                            Id = 3,
                            ConsumableId = 3,
                            QuantityOnHand = 25,
                            WardName = "Ward A"
                        },
                        new
                        {
                            Id = 4,
                            ConsumableId = 4,
                            QuantityOnHand = 75,
                            WardName = "Ward C"
                        },
                        new
                        {
                            Id = 5,
                            ConsumableId = 5,
                            QuantityOnHand = 150,
                            WardName = "Emergency"
                        },
                        new
                        {
                            Id = 6,
                            ConsumableId = 6,
                            QuantityOnHand = 40,
                            WardName = "ICU"
                        },
                        new
                        {
                            Id = 7,
                            ConsumableId = 7,
                            QuantityOnHand = 30,
                            WardName = "Ward B"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "role-doctor",
                            Name = "Doctor",
                            NormalizedName = "DOCTOR"
                        },
                        new
                        {
                            Id = "role-stock",
                            Name = "StockManager",
                            NormalizedName = "STOCKMANAGER"
                        },
                        new
                        {
                            Id = "role-script",
                            Name = "ScriptManager",
                            NormalizedName = "SCRIPTMANAGER"
                        },
                        new
                        {
                            Id = "role-admin",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "role-nurse",
                            Name = "Nurse",
                            NormalizedName = "NURSE"
                        },
                        new
                        {
                            Id = "role-nursing-sister",
                            Name = "NursingSister",
                            NormalizedName = "NURSINGSISTER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("HealthOps_Project.Models.Admission", b =>
                {
                    b.HasOne("HealthOps_Project.Models.Bed", "Bed")
                        .WithMany("Admissions")
                        .HasForeignKey("BedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthOps_Project.Models.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthOps_Project.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthOps_Project.Models.Ward", "Ward")
                        .WithMany("Admissions")
                        .HasForeignKey("WardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bed");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");

                    b.Navigation("Ward");
                });

            modelBuilder.Entity("HealthOps_Project.Models.Appointment", b =>
                {
                    b.HasOne("HealthOps_Project.Models.ApplicationUser", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthOps_Project.Models.Patient", null)
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId");

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("HealthOps_Project.Models.Bed", b =>
                {
                    b.HasOne("HealthOps_Project.Models.Patient", "Patient")
                        .WithOne("Bed")
                        .HasForeignKey("HealthOps_Project.Models.Bed", "PatientId");

                    b.HasOne("HealthOps_Project.Models.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId");

                    b.HasOne("HealthOps_Project.Models.Ward", "Ward")
                        .WithMany("Beds")
                        .HasForeignKey("WardId");

                    b.Navigation("Patient");

                    b.Navigation("Room");

                    b.Navigation("Ward");
                });

            modelBuilder.Entity("HealthOps_Project.Models.ConsumableRequest", b =>
                {
                    b.HasOne("HealthOps_Project.Models.Consumable", "Consumable")
                        .WithMany()
                        .HasForeignKey("ConsumableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consumable");
                });

            modelBuilder.Entity("HealthOps_Project.Models.Diagnosis", b =>
                {
                    b.HasOne("HealthOps_Project.Models.Doctor", "Doctor")
                        .WithMany("Diagnoses")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthOps_Project.Models.Patient", "Patient")
                        .WithMany("Diagnoses")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthOps_Project.Models.Symptom", "Symptom")
                        .WithMany()
                        .HasForeignKey("SymptomId");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");

                    b.Navigation("Symptom");
                });

            modelBuilder.Entity("HealthOps_Project.Models.Discharge", b =>
                {
                    b.HasOne("HealthOps_Project.Models.Patient", "Patient")
                        .WithMany("Discharges")
                        .HasForeignKey("PatientId");

                    b.HasOne("HealthOps_Project.Models.Ward", "Ward")
                        .WithMany()
                        .HasForeignKey("WardId");

                    b.Navigation("Patient");

                    b.Navigation("Ward");
                });

            modelBuilder.Entity("HealthOps_Project.Models.DoctorInstruction", b =>
                {
                    b.HasOne("HealthOps_Project.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HealthOps_Project.Models.MedicationAdministration", b =>
                {
                    b.HasOne("HealthOps_Project.Models.Medication", "Medication")
                        .WithMany()
                        .HasForeignKey("MedicationId");

                    b.HasOne("HealthOps_Project.Models.Patient", "Patient")
                        .WithMany("MedicationAdministrations")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthOps_Project.Models.Prescription", "Prescription")
                        .WithMany("MedicationAdministrations")
                        .HasForeignKey("PrescriptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthOps_Project.Models.Prescription", null)
                        .WithMany("AdministrationRecords")
                        .HasForeignKey("PrescriptionId1");

                    b.Navigation("Medication");

                    b.Navigation("Patient");

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("HealthOps_Project.Models.MedicationDelivery", b =>
                {
                    b.HasOne("HealthOps_Project.Models.Medication", "Medication")
                        .WithMany()
                        .HasForeignKey("MedicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthOps_Project.Models.Prescription", "Prescription")
                        .WithMany("MedicationDeliveries")
                        .HasForeignKey("PrescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthOps_Project.Models.Script", "Script")
                        .WithMany("MedicationDeliveries")
                        .HasForeignKey("ScriptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Medication");

                    b.Navigation("Prescription");

                    b.Navigation("Script");
                });

            modelBuilder.Entity("HealthOps_Project.Models.NonScheduledMedication", b =>
                {
                    b.HasOne("HealthOps_Project.Models.Medication", "Medication")
                        .WithMany()
                        .HasForeignKey("MedicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medication");
                });

            modelBuilder.Entity("HealthOps_Project.Models.NurseInstruction", b =>
                {
                    b.HasOne("HealthOps_Project.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HealthOps_Project.Models.Patient", b =>
                {
                    b.HasOne("HealthOps_Project.Models.ApplicationUser", "DoctorUser")
                        .WithMany()
                        .HasForeignKey("DoctorUserId");

                    b.HasOne("HealthOps_Project.Models.Ward", "Ward")
                        .WithMany()
                        .HasForeignKey("WardId");

                    b.Navigation("DoctorUser");

                    b.Navigation("Ward");
                });

            modelBuilder.Entity("HealthOps_Project.Models.PatientHistory", b =>
                {
                    b.HasOne("HealthOps_Project.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HealthOps_Project.Models.PatientMovement", b =>
                {
                    b.HasOne("HealthOps_Project.Models.Patient", "Patient")
                        .WithMany("PatientMovements")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthOps_Project.Models.Room", "Room")
                        .WithMany("PatientMovements")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("HealthOps_Project.Models.Prescription", b =>
                {
                    b.HasOne("HealthOps_Project.Models.Doctor", null)
                        .WithMany("Prescriptions")
                        .HasForeignKey("DoctorId");

                    b.HasOne("HealthOps_Project.Models.Patient", "Patient")
                        .WithMany("Prescriptions")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HealthOps_Project.Models.PrescriptionDelivery", b =>
                {
                    b.HasOne("HealthOps_Project.Models.Prescription", "Prescription")
                        .WithMany("PrescriptionDeliveries")
                        .HasForeignKey("PrescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("HealthOps_Project.Models.ScheduledMedication", b =>
                {
                    b.HasOne("HealthOps_Project.Models.Medication", "Medication")
                        .WithMany()
                        .HasForeignKey("MedicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medication");
                });

            modelBuilder.Entity("HealthOps_Project.Models.Script", b =>
                {
                    b.HasOne("HealthOps_Project.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HealthOps_Project.Models.Stocktake", b =>
                {
                    b.HasOne("HealthOps_Project.Models.Consumable", "Consumable")
                        .WithMany()
                        .HasForeignKey("ConsumableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consumable");
                });

            modelBuilder.Entity("HealthOps_Project.Models.Symptom", b =>
                {
                    b.HasOne("HealthOps_Project.Models.Patient", "Patient")
                        .WithMany("Symptoms")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HealthOps_Project.Models.Treatment", b =>
                {
                    b.HasOne("HealthOps_Project.Models.Patient", "Patient")
                        .WithMany("Treatments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HealthOps_Project.Models.Visitation", b =>
                {
                    b.HasOne("HealthOps_Project.Models.Doctor", null)
                        .WithMany("Visitations")
                        .HasForeignKey("DoctorId");

                    b.HasOne("HealthOps_Project.Models.Patient", "Patient")
                        .WithMany("Visits")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HealthOps_Project.Models.VitalSign", b =>
                {
                    b.HasOne("HealthOps_Project.Models.Patient", "Patient")
                        .WithMany("VitalSigns")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HealthOps_Project.Models.WardStock", b =>
                {
                    b.HasOne("HealthOps_Project.Models.Consumable", "Consumable")
                        .WithMany()
                        .HasForeignKey("ConsumableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consumable");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("HealthOps_Project.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("HealthOps_Project.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthOps_Project.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("HealthOps_Project.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HealthOps_Project.Models.Bed", b =>
                {
                    b.Navigation("Admissions");
                });

            modelBuilder.Entity("HealthOps_Project.Models.Doctor", b =>
                {
                    b.Navigation("Diagnoses");

                    b.Navigation("Prescriptions");

                    b.Navigation("Visitations");
                });

            modelBuilder.Entity("HealthOps_Project.Models.Patient", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Bed");

                    b.Navigation("Diagnoses");

                    b.Navigation("Discharges");

                    b.Navigation("MedicationAdministrations");

                    b.Navigation("PatientMovements");

                    b.Navigation("Prescriptions");

                    b.Navigation("Symptoms");

                    b.Navigation("Treatments");

                    b.Navigation("Visits");

                    b.Navigation("VitalSigns");
                });

            modelBuilder.Entity("HealthOps_Project.Models.Prescription", b =>
                {
                    b.Navigation("AdministrationRecords");

                    b.Navigation("MedicationAdministrations");

                    b.Navigation("MedicationDeliveries");

                    b.Navigation("PrescriptionDeliveries");
                });

            modelBuilder.Entity("HealthOps_Project.Models.Room", b =>
                {
                    b.Navigation("PatientMovements");
                });

            modelBuilder.Entity("HealthOps_Project.Models.Script", b =>
                {
                    b.Navigation("MedicationDeliveries");
                });

            modelBuilder.Entity("HealthOps_Project.Models.Ward", b =>
                {
                    b.Navigation("Admissions");

                    b.Navigation("Beds");
                });
#pragma warning restore 612, 618
        }
    }
}
